runtime: nodejs18
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: 1 # Ensures there is always at least one idle instance
  max_idle_instances: 5 # Limits the number of idle instances to control costs
  target_cpu_utilization: 0.6 # Adjusts instances based on CPU usage
  max_concurrent_requests: 50 # Adjust to manage load per instance

